In [1]:
import pandas as pd
import numpy as np
import requests
import json
import pandas as pd
from itertools import tee

In [4]:
df = pd.read_csv("Clusters+vert_cercanos.csv", delimiter=",")

In [5]:
df

,Unnamed: 0,x,y,index_vertice_cercano,LATITUD,LONGITUD,distancia_h
0,0,4.124433,-73.627487,33483,4.124,-73.627545,0.048541
1,1,4.118694,-73.563922,37514,4.119,-73.563647,0.045658
2,2,4.075202,-73.672954,52077,4.075,-73.672891,0.023477
3,3,4.153048,-73.599674,11110,4.153,-73.599651,0.005913
4,4,4.148361,-73.613292,14637,4.148,-73.613417,0.042406
...,...,...,...,...,...,...,...
195,195,4.158273,-73.651119,7341,4.158,-73.651163,0.030774
196,196,4.103017,-73.659508,45497,4.103,-73.659841,0.036985
197,197,4.155809,-73.632643,8546,4.156,-73.632766,0.025231
198,198,4.136147,-73.609554,23612,4.136,-73.609601,0.017196
199,199,4.119560,-73.609358,37039,4.120,-73.609399,0.049086

In [8]:
df_colegios = pd.read_csv("Colegios_oficiales.csv", delimiter=";")

In [33]:
array_idsede=df_colegios.id_sede.values

In [36]:
df2=df.copy(deep=True)

In [48]:
for col_name in array_idsede:
    df2[col_name] = None

In [49]:
for col_name in array_idsede2:
    df2[col_name] = None

In [56]:
df2 = df2.drop(array_idsede2, axis=1)

In [9]:
df_colegios

     id_sede   latitud   longitud
0        827  4.123157 -73.541060
1        937  4.147969 -73.643800
2        945  4.140322 -73.622633
3        946  4.131999 -73.635603
4        961  4.109037 -73.652828
..       ...       ...        ...
158    82627  4.134287 -73.611144
159    85626  3.981392 -73.237248
160    85906  4.139800 -73.614421
161    86871  3.981392 -73.237248
162    87062  3.981392 -73.237248

[163 rows x 3 columns]

In [1]:
#Se quita por motivos de seguridad
key_API_google=""

In [12]:
origenes=[]
DENUEVO['pair_orig']=DENUEVO['Latitud_NS'].astype(str)+"%2C"+DENUEVO['Longitud_NS'].astype(str)

In [14]:
origenes = [row['LATITUD'].astype(str)+"%2C"+row['LONGITUD'].astype(str) for index, row in df.iterrows()]

In [23]:
destinos = [row['latitud'].astype(str)+"%2C"+row['longitud'].astype(str) for index, row in df_colegios.iterrows()]

In [24]:
destinos

['4.123157307%2C-73.54105965',
 '4.147969444%2C-73.6438',
 '4.140322222%2C-73.62263333',
 '4.13199908%2C-73.63560324',
 '4.109037352%2C-73.65282838',
 '4.073460215%2C-73.67090286',
 '4.143086222%2C-73.58588198',
 '4.097763049%2C-73.62964022',
 '4.143867%2C-73.630029',
 '4.118373908%2C-73.6004798',
 '4.118373908%2C-73.6004798',
 '3.981392%2C-73.237248',
 '3.981392%2C-73.237248',
 '4.139620352%2C-73.60787728',
 '4.076590072%2C-73.67337136',
 '4.109925749%2C-73.64888105',
 '4.140976696%2C-73.59018497',
 '4.127289714%2C-73.63696281',
 '4.136205842%2C-73.63441754',
 '3.981392%2C-73.237248',
 '4.122547222%2C-73.63390278',
 '4.151222%2C-73.613112',
 '4.12824515%2C-73.58819413',
 '4.159003154%2C-73.65173186',
 '4.13636201%2C-73.62455921',
 '4.160285%2C-73.645764',
 '3.981392%2C-73.237248',
 '3.981392%2C-73.237248',
 '4.122995054%2C-73.54173279',
 '4.136155543%2C-73.63265483',
 '3.981392%2C-73.237248',
 '4.13199908%2C-73.63560324',
 '3.981392%2C-73.237248',
 '4.13636201%2C-73.62455921',
 '4.136362107%2C-73.62455908',
 '4.15149096%2C-73.59466419',
 '4.154025407%2C-73.63877547',
 '4.156477894%2C-73.65817637',
 '4.126071083%2C-73.62820631',
 '4.121876356%2C-73.62142364',
 '4.139320713%2C-73.58687307',
 '4.124005806%2C-73.64907882',
 '4.15899671%2C-73.65580331',
 '4.149509371%2C-73.6309426',
 '4.10869%2C-73.65255',
 '3.981392%2C-73.237248',
 '4.15102987%2C-73.61344253',
 '4.119115027%2C-73.64541596',
 '4.129786878%2C-73.6313594',
 '4.120032771%2C-73.59605069',
 '4.118373908%2C-73.6004798',
 '4.154038635%2C-73.61902289',
 '4.124731379%2C-73.62213917',
 '3.981392%2C-73.237248',
 '4.130315049%2C-73.62146688',
 '4.126757955%2C-73.6139531',
 '4.083618957%2C-73.66780306',
 '4.142809388%2C-73.62534701',
 '3.981392%2C-73.237248',
 '3.981392%2C-73.237248',
 '3.981392%2C-73.237248',
 '3.981392%2C-73.237248',
 '4.139995067%2C-73.63412916',
 '4.073608333%2C-73.67074444',
 '4.134385959%2C-73.63304308',
 '4.158996713%2C-73.65580331',
 '4.08177004%2C-73.6718775',
 '4.129139%2C-73.655726',
 '4.160078033%2C-73.65475734',
 '3.981392%2C-73.237248',
 '3.981392%2C-73.237248',
 '4.160570264%2C-73.64304459',
 '3.981392%2C-73.237248',
 '4.136521274%2C-73.62794082',
 '4.13711655%2C-73.60920235',
 '4.129932386%2C-73.59223324',
 '4.119115027%2C-73.64541596',
 '4.157008897%2C-73.6334711',
 '3.981392%2C-73.237248',
 '4.148261465%2C-73.6254639',
 '3.981392%2C-73.237248',
 '3.981392%2C-73.237248',
 '3.981392%2C-73.237248',
 '4.160570264%2C-73.64304459',
 '4.152384445%2C-73.60713802',
 '4.132139321%2C-73.62947066',
 '4.154071215%2C-73.63130819',
 '4.129832516%2C-73.63600798',
 '4.132150106%2C-73.62769636',
 '3.981392%2C-73.237248',
 '4.151397962%2C-73.62307874',
 '4.081784721%2C-73.67067168',
 '4.117991667%2C-73.62720278',
 '4.118291667%2C-73.62555556',
 '4.139018821%2C-73.60853391',
 '4.158459108%2C-73.63796136',
 '3.981392%2C-73.237248',
 '3.981392%2C-73.237248',
 '4.137148978%2C-73.63076904',
 '4.141108333%2C-73.63796389',
 '3.981392%2C-73.237248',
 '4.139492744%2C-73.62852761',
 '4.122769689%2C-73.62785278',
 '4.104504776%2C-73.64943744',
 '3.981392%2C-73.237248',
 '3.981392%2C-73.237248',
 '4.151270326%2C-73.62689858',
 '4.129545543%2C-73.61196538',
 '4.12960226%2C-73.54624405',
 '4.13942533%2C-73.58031056',
 '4.14555564%2C-73.62789838',
 '4.137972374%2C-73.62851575',
 '4.135558833%2C-73.62707746',
 '4.141605632%2C-73.63822101',
 '4.144279215%2C-73.61627771',
 '4.102566112%2C-73.64989435',
 '3.981392%2C-73.237248',
 '3.981392%2C-73.237248',
 '3.981392%2C-73.237248',
 '4.139620352%2C-73.60787728',
 '4.139536141%2C-73.62805662',
 '4.15814627%2C-73.64216919',
 '4.146030832%2C-73.61097793',
 '4.118697222%2C-73.62877778',
 '3.981392%2C-73.237248',
 '3.981392%2C-73.237248',
 '4.119115027%2C-73.64541596',
 '4.139674376%2C-73.6140296',
 '4.113124299%2C-73.61299943',
 '4.134416098%2C-73.58908267',
 '4.115413132%2C-73.59771476',
 '4.131404262%2C-73.60884064',
 '4.123042426%2C-73.5631774',
 '4.13199908%2C-73.63560324',
 '4.126513%2C-73.626712',
 '4.12915381%2C-73.63475871',
 '4.144887%2C-73.630593',
 '4.148742943%2C-73.63543347',
 '4.149509371%2C-73.6309426',
 '4.139492744%2C-73.62852761',
 '4.148687533%2C-73.60465138',
 '4.134546287%2C-73.60910989',
 '3.981392%2C-73.237248',
 '4.129136%2C-73.634912',
 '4.142297%2C-73.62558',
 '4.07592%2C-73.67425',
 '4.140887752%2C-73.63088707',
 '4.160221301%2C-73.64774455',
 '4.133071589%2C-73.62013623',
 '4.131020626%2C-73.6144743',
 '4.130325239%2C-73.61192991',
 '4.157008897%2C-73.6334711',
 '3.981392%2C-73.237248',
 '4.117367855%2C-73.58485335',
 '4.14995%2C-73.63113611',
 '4.147881764%2C-73.6217978',
 '4.132139321%2C-73.62947066',
 '4.148261465%2C-73.6254639',
 '4.134287455%2C-73.6111443',
 '3.981392%2C-73.237248',
 '4.1398%2C-73.614421',
 '3.981392%2C-73.237248',
 '3.981392%2C-73.237248']

In [18]:
origenes

['4.124432932948718%2C-73.62748715871795',
 '4.118693924058824%2C-73.56392190735293',
 '4.075201501967742%2C-73.6729542432258',
 '4.153048165722222%2C-73.59967378',
 '4.148360620941176%2C-73.61329178294118',
 '4.105292071636364%2C-73.65362448',
 '4.1393397436875%2C-73.638022381875',
 '4.119413893842105%2C-73.59579037631579',
 '4.120591631818182%2C-73.53608037090909',
 '4.161972255%2C-73.65144976060606',
 '4.142513901102564%2C-73.58422465974358',
 '4.0635941438181815%2C-73.50386596272728',
 '4.0569697906%2C-73.59781528',
 '4.12886386688%2C-73.6121985376',
 '4.081513973333333%2C-73.69717485041667',
 '4.079801727%2C-73.70425134666667',
 '4.104822860625%2C-73.6234973975',
 '4.15245332937931%2C-73.63068707034483',
 '4.121572563125%2C-73.64667114125',
 '4.060175117269231%2C-73.67260199461538',
 '4.125357067630435%2C-73.54822033673913',
 '4.079279571567568%2C-73.66977230054054',
 '4.134051636761905%2C-73.62016046547619',
 '4.132240934106383%2C-73.59081790553192',
 '4.103601826162162%2C-73.64509862054054',
 '4.1712367498%2C-73.62701252400001',
 '4.139274398942857%2C-73.61569393257143',
 '4.090270860457143%2C-73.665825128',
 '4.130151348066667%2C-73.62950556033333',
 '4.114862376322581%2C-73.5846919916129',
 '4.143112886555556%2C-73.65143759277778',
 '4.087690467333333%2C-73.55793627166666',
 '4.146675544568182%2C-73.62748241772726',
 '4.157718301583333%2C-73.63524602166666',
 '4.148211629583333%2C-73.63738110458333',
 '4.1100709969375%2C-73.6625664584375',
 '4.151651330125%2C-73.6225862375',
 '4.119205127434783%2C-73.62720291717392',
 '4.145161031341464%2C-73.60992803707317',
 '4.1143913523333335%2C-73.61148827',
 '4.1002216957115385%2C-73.63755167673077',
 '4.147039134244444%2C-73.58986576533333',
 '4.149346372088235%2C-73.60733515852941',
 '4.169989865833333%2C-73.67986296166666',
 '4.114279197326924%2C-73.55748267153847',
 '4.127960792785714%2C-73.63599687571428',
 '4.1211538737%2C-73.564169726',
 '4.135558975147059%2C-73.6064844582353',
 '4.134406363239131%2C-73.58677202413044',
 '4.0817274714166665%2C-73.66295618266666',
 '4.100902944270271%2C-73.65221387918919',
 '4.1301063823333335%2C-73.58641537833333',
 '4.150222928857143%2C-73.58518178761905',
 '4.159546858714286%2C-73.64200272928571',
 '4.0756062246%2C-73.58547391',
 '4.148765858911765%2C-73.64216421294118',
 '4.156258064958333%2C-73.655782125',
 '4.0939798875%2C-73.48386893',
 '4.12813486953125%2C-73.616910925',
 '4.134299335306123%2C-73.62928631326531',
 '4.102483659058824%2C-73.6160939617647',
 '4.122720709473684%2C-73.63432712710527',
 '4.107437819708333%2C-73.65922692291666',
 '4.153099893846154%2C-73.61442096711538',
 '4.124690521257143%2C-73.65270956257143',
 '4.112319789896552%2C-73.61540382413793',
 '4.086048590184211%2C-73.65841514078947',
 '4.138923562469388%2C-73.62367844489796',
 '4.071887298181818%2C-73.67002792454545',
 '4.134144316783784%2C-73.6122679372973',
 '4.1183139716333335%2C-73.591271412',
 '4.127339661204545%2C-73.54515553045455',
 '4.099483423038461%2C-73.65755152538462',
 '4.068164818733333%2C-73.66482641866666',
 '4.159701517%2C-73.66177470285714',
 '4.074998235428572%2C-73.68010257571429',
 '4.130769704171429%2C-73.63285283914286',
 '4.1555603668108105%2C-73.6283781145946',
 '4.1800550728%2C-73.615546372',
 '4.148324008594595%2C-73.62404593405405',
 '4.146361071%2C-73.60495105814815',
 '4.056890493096774%2C-73.67586342483871',
 '4.120377609521739%2C-73.62286904434782',
 '4.1098981465%2C-73.63152095',
 '4.145955974565218%2C-73.61667119456521',
 '4.140034271814815%2C-73.6322664762963',
 '4.1236625104%2C-73.5428806575',
 '4.1672487906%2C-73.630978898',
 '4.118784479205883%2C-73.59872876411765',
 '4.098555165690476%2C-73.6446326897619',
 '4.140228361027778%2C-73.58813822138889',
 '4.0777613104%2C-73.67624302577778',
 '4.074609684333334%2C-73.71145359666666',
 '4.106177429975%2C-73.64762672125',
 '4.139230288607143%2C-73.64330564',
 '4.150125080909091%2C-73.58140629454546',
 '4.160378666096774%2C-73.65482981967742',
 '4.128122130517242%2C-73.62653893931035',
 '4.150974731115385%2C-73.59446626038462',
 '4.067632442%2C-73.67125230529412',
 '4.14075678675%2C-73.60751180916667',
 '4.121841140787879%2C-73.53362768484848',
 '4.1473052510277775%2C-73.63169295444445',
 '4.10574910725%2C-73.591799275',
 '4.0775801265%2C-73.565867975',
 '4.137426685866667%2C-73.64744496666667',
 '4.151321028896552%2C-73.61853692896551',
 '4.100953409214286%2C-73.629676575',
 '4.114321280085714%2C-73.62373591742858',
 '4.120461640428571%2C-73.56116841392857',
 '4.115677036809524%2C-73.60624313238095',
 '4.17152865225%2C-73.6394791525',
 '4.142369882054054%2C-73.61748808',
 '4.0947417606%2C-73.558434902',
 '4.115057795882353%2C-73.5876838417647',
 '4.1307446913%2C-73.60068255499999',
 '4.122749311769231%2C-73.6250903648718',
 '4.084997167%2C-73.61318681',
 '4.165490611875%2C-73.6217862675',
 '4.083371772777777%2C-73.66779225407407',
 '4.129656058709678%2C-73.61875895096775',
 '4.13127561932%2C-73.609278448',
 '4.157211522333333%2C-73.64600055733334',
 '4.135226932363636%2C-73.6336909878788',
 '4.104942316%2C-73.55800413',
 '4.130314677357143%2C-73.54875033535714',
 '4.1083462468205125%2C-73.65157055333333',
 '4.118415745071428%2C-73.65130978428571',
 '4.160585473827586%2C-73.63865042896552',
 '4.1313208432%2C-73.655322984',
 '4.145065358953488%2C-73.5862984239535',
 '4.1438389572666665%2C-73.640434014',
 '4.141946259181818%2C-73.61201521945455',
 '4.152395645125%2C-73.607003101875',
 '4.139754138551724%2C-73.5814065662069',
 '4.151032043%2C-73.65885594166667',
 '4.152522825857143%2C-73.6353530147619',
 '4.118661134633333%2C-73.63179229133334',
 '4.1549069741428575%2C-73.57290907142857',
 '4.143140738368421%2C-73.62317536578948',
 '4.083974255285714%2C-73.67847917142858',
 '4.111795434777778%2C-73.64046754',
 '4.126324559172414%2C-73.56582446482759',
 '4.115545332025%2C-73.59752621724999',
 '4.12390866952174%2C-73.62138087869565',
 '4.155111441538462%2C-73.63914028307693',
 '4.102879996823529%2C-73.6490695767647',
 '4.09867112136%2C-73.6490542134',
 '4.125289107942857%2C-73.63242482971428',
 '4.1189295742272725%2C-73.58543954045454',
 '4.064250883526316%2C-73.66911816947368',
 '4.150826584733333%2C-73.59093556466667',
 '4.146841088344828%2C-73.64489847724138',
 '4.0977012456%2C-73.663652306',
 '4.136162250791667%2C-73.6007655525',
 '4.132589654735294%2C-73.61649316970588',
 '4.092342347%2C-73.62203724',
 '4.161066269777778%2C-73.64699510111112',
 '4.129629647545455%2C-73.56898952',
 '4.057232855483871%2C-73.67254314193548',
 '4.06759333125%2C-73.5928780775',
 '4.075802471034483%2C-73.66875547931035',
 '4.04835367075%2C-73.60030057',
 '4.142159164184211%2C-73.62792514526316',
 '4.151323237733333%2C-73.62762782',
 '4.1058975543%2C-73.66290445866666',
 '4.0793912355172415%2C-73.67313606137931',
 '4.127061639636364%2C-73.62963049848484',
 '4.13896555502381%2C-73.58498892142858',
 '4.1261851399375%2C-73.61494653125',
 '4.136029213115385%2C-73.59099852576924',
 '4.0832106648928574%2C-73.67130483464285',
 '4.125050981714286%2C-73.58683053857143',
 '4.116503983714286%2C-73.56112998828571',
 '4.1432343%2C-73.63565303833333',
 '4.135798985095238%2C-73.63958119142858',
 '4.179955167%2C-73.64224186',
 '4.129369044111111%2C-73.59018824622223',
 '4.068936007571429%2C-73.66791155857143',
 '4.173713471538462%2C-73.62196575153845',
 '4.13733136225%2C-73.612859223125',
 '4.116086118368421%2C-73.61756163894736',
 '4.1292759795%2C-73.64439974833334',
 '4.132601811%2C-73.63606588230769',
 '4.131000419034483%2C-73.62101148793103',
 '4.149885333361111%2C-73.61641338111112',
 '4.153176348444444%2C-73.6025633338889',
 '4.125651559351351%2C-73.56257940594595',
 '4.091320923%2C-73.63372374',
 '4.122024553584906%2C-73.53905904056603',
 '4.135030603434783%2C-73.62365157347826',
 '4.13669779790625%2C-73.6172747971875',
 '4.122630833657895%2C-73.6305404618421',
 '4.153516323891892%2C-73.61951968945945',
 '4.148941142730769%2C-73.62027217461538',
 '4.158273343592593%2C-73.65111892666667',
 '4.103017430647059%2C-73.65950797882353',
 '4.155808680227272%2C-73.63264340863637',
 '4.136147464697674%2C-73.60955398302326',
 '4.119560204428572%2C-73.60935761']

In [32]:
len(todas_solicitudes[0])

163

In [27]:
todas_solicitudes=[]
for i in range(len(origenes)):
    solicitudes=[]
    for j in range(len(destinos)):
        solicitud="https://maps.googleapis.com/maps/api/distancematrix/json?destinations="+destinos[j]+"&origins="+origenes[i]+"&key="+key_API_google
        solicitudes.append(solicitud)
    todas_solicitudes.append(solicitudes)

In [51]:
todas_solicitudes2 = pd.DataFrame(todas_solicitudes)

In [53]:
def solicitud_maps(url):
    try:
        payload = {}
        headers = {}
        response = requests.request("GET", url, headers=headers, data=payload)
        x = response.json()
        drive_time_seconds = x['rows'][0]['elements'][0]['duration']['value']
        distance_meters = x['rows'][0]['elements'][0]['distance']['value']
        return [drive_time_seconds, distance_meters]
    except KeyError:
        return 0

In [65]:
df2[827] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[0]), axis=1)

In [68]:
df2[937] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[1]), axis=1)
df2[945] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[2]), axis=1)
df2[946] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[3]), axis=1)
df2[961] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[4]), axis=1)

In [70]:
df2[969] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[5]), axis=1)
df2[970] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[6]), axis=1)
df2[971] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[7]), axis=1)
df2[3876] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[8]), axis=1)
df2[4067] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[9]), axis=1)
df2[4068] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[10]), axis=1)
df2[4174] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[11]), axis=1)
df2[4230] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[12]), axis=1)
df2[4231] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[13]), axis=1)
df2[5409] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[14]), axis=1)

In [72]:
df2[5888] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[16]), axis=1)
df2[6439] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[17]), axis=1)
df2[6440] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[18]), axis=1)
df2[6449] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[19]), axis=1)
df2[6472] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[20]), axis=1)
df2[6473] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[21]), axis=1)
df2[6474] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[22]), axis=1)
df2[6617] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[23]), axis=1)
df2[9710] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[24]), axis=1)
df2[9711] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[25]), axis=1)
df2[9726] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[26]), axis=1)
df2[10827] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[27]), axis=1)
df2[10887] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[28]), axis=1)
df2[11756] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[29]), axis=1)
df2[11757] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[30]), axis=1)
df2[11758] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[31]), axis=1)
df2[15123] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[32]), axis=1)
df2[15147] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[33]), axis=1)
df2[17213] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[34]), axis=1)
df2[17225] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[35]), axis=1)
df2[17323] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[36]), axis=1)
df2[17343] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[37]), axis=1)
df2[17359] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[38]), axis=1)
df2[17360] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[39]), axis=1)
df2[17379] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[40]), axis=1)
df2[17380] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[41]), axis=1)
df2[20609] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[42]), axis=1)
df2[20610] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[43]), axis=1)
df2[20622] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[44]), axis=1)
df2[20623] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[45]), axis=1)

In [73]:
df2[5588] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[15]), axis=1)

In [74]:
df2[20624] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[46]), axis=1)
df2[22639] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[47]), axis=1)
df2[22783] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[48]), axis=1)
df2[22798] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[49]), axis=1)
df2[25819] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[50]), axis=1)
df2[27262] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[51]), axis=1)
df2[27943] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[52]), axis=1)
df2[28069] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[53]), axis=1)
df2[28116] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[54]), axis=1)
df2[28117] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[55]), axis=1)
df2[28118] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[56]), axis=1)
df2[31119] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[57]), axis=1)
df2[31422] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[58]), axis=1)
df2[31433] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[59]), axis=1)
df2[32521] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[60]), axis=1)
df2[32522] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[61]), axis=1)
df2[33473] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[62]), axis=1)
df2[33491] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[63]), axis=1)
df2[33585] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[64]), axis=1)
df2[33609] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[65]), axis=1)
df2[33624] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[66]), axis=1)
df2[35091] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[67]), axis=1)
df2[36695] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[68]), axis=1)
df2[36974] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[69]), axis=1)
df2[38150] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[70]), axis=1)
df2[38534] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[71]), axis=1)
df2[39041] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[72]), axis=1)
df2[39156] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[73]), axis=1)
df2[39166] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[74]), axis=1)
df2[39193] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[75]), axis=1)

In [75]:
df2[39194] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[76]), axis=1)
df2[39357] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[77]), axis=1)
df2[42458] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[78]), axis=1)
df2[42459] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[79]), axis=1)
df2[42470] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[80]), axis=1)
df2[42471] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[81]), axis=1)
df2[42472] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[82]), axis=1)
df2[44022] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[83]), axis=1)
df2[44499] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[84]), axis=1)
df2[44622] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[85]), axis=1)
df2[44623] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[86]), axis=1)
df2[44624] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[87]), axis=1)
df2[44633] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[88]), axis=1)
df2[44634] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[89]), axis=1)
df2[44658] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[90]), axis=1)
df2[44659] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[91]), axis=1)
df2[44675] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[92]), axis=1)
df2[44676] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[93]), axis=1)
df2[44677] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[94]), axis=1)
df2[44825] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[95]), axis=1)
df2[47941] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[96]), axis=1)
df2[47942] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[97]), axis=1)
df2[49556] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[98]), axis=1)
df2[50086] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[99]), axis=1)
df2[50105] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[100]), axis=1)
df2[50131] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[101]), axis=1)
df2[50132] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[102]), axis=1)
df2[50133] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[103]), axis=1)
df2[53111] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[104]), axis=1)
df2[53406] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[105]), axis=1)

In [76]:
df2[53407] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[106]), axis=1)
df2[53419] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[107]), axis=1)
df2[54504] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[108]), axis=1)
df2[55534] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[109]), axis=1)
df2[55535] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[110]), axis=1)
df2[55549] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[111]), axis=1)
df2[55550] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[112]), axis=1)
df2[55558] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[113]), axis=1)
df2[55579] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[114]), axis=1)
df2[55591] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[115]), axis=1)
df2[58580] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[116]), axis=1)
df2[58877] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[117]), axis=1)
df2[58884] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[118]), axis=1)
df2[60967] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[119]), axis=1)
df2[60979] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[120]), axis=1)
df2[61175] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[121]), axis=1)
df2[62527] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[122]), axis=1)
df2[62528] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[123]), axis=1)
df2[63981] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[124]), axis=1)
df2[65066] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[125]), axis=1)
df2[66136] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[126]), axis=1)
df2[66299] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[127]), axis=1)
df2[66323] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[128]), axis=1)
df2[66324] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[129]), axis=1)
df2[66325] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[130]), axis=1)
df2[66341] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[131]), axis=1)
df2[69339] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[132]), axis=1)
df2[69481] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[133]), axis=1)
df2[69482] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[134]), axis=1)

In [77]:
df2[71574] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[135]), axis=1)
df2[71575] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[136]), axis=1)
df2[71576] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[137]), axis=1)
df2[71584] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[138]), axis=1)
df2[71615] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[139]), axis=1)
df2[71616] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[140]), axis=1)
df2[71617] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[141]), axis=1)
df2[74882] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[142]), axis=1)
df2[74897] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[143]), axis=1)
df2[74898] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[144]), axis=1)
df2[77000] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[145]), axis=1)
df2[77120] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[146]), axis=1)
df2[77121] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[147]), axis=1)
df2[77129] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[148]), axis=1)
df2[77160] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[149]), axis=1)
df2[77161] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[150]), axis=1)
df2[80410] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[151]), axis=1)
df2[81555] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[152]), axis=1)
df2[82443] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[153]), axis=1)
df2[82576] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[154]), axis=1)
df2[82577] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[155]), axis=1)
df2[82595] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[156]), axis=1)
df2[82596] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[157]), axis=1)
df2[82627] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[158]), axis=1)
df2[85626] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[159]), axis=1)
df2[85906] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[160]), axis=1)
df2[86871] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[161]), axis=1)
df2[87062] = todas_solicitudes2.apply(lambda x: solicitud_maps(x[162]), axis=1)

In [67]:
df2[827]

0      [1623, 11943]
1        [783, 5541]
2      [2358, 20737]
3       [1338, 9636]
4       [1160, 9432]
           ...
195    [1911, 14381]
196    [1977, 17208]
197    [1547, 11967]
198     [1168, 9322]
199    [1395, 11652]
Name: 827, Length: 200, dtype: object

In [79]:
df2.to_csv("FINAL2.csv",index=True)

In [80]:
df2

,Unnamed: 0,x,y,index_vertice_cercano,LATITUD,LONGITUD,distancia_h,827,937,945,...,82443,82576,82577,82595,82596,82627,85626,85906,86871,87062
0,0,4.124433,-73.627487,33483,4.124,-73.627545,0.048541,"[1623, 11943]","[839, 4003]","[512, 2787]",...,"[828, 5685]","[715, 4152]","[649, 3445]","[298, 1205]","[641, 4117]","[686, 3269]","[3690, 50899]","[691, 3405]","[3690, 50899]","[3690, 50899]"
1,1,4.118694,-73.563922,37514,4.119,-73.563647,0.045658,"[783, 5541]","[1636, 11537]","[1142, 9199]",...,"[498, 3620]","[1282, 9980]","[1029, 8747]","[1236, 9575]","[1143, 9302]","[888, 6640]","[4335, 56462]","[994, 8488]","[4335, 56462]","[4335, 56462]"
2,2,4.075202,-73.672954,52077,4.075,-73.672891,0.023477,"[2358, 20737]","[1356, 10448]","[1333, 10641]",...,"[1630, 13774]","[1302, 10701]","[1297, 11109]","[1144, 9402]","[1240, 10701]","[1562, 11642]","[4412, 58545]","[1568, 11777]","[4412, 58545]","[4412, 58545]"
3,3,4.153048,-73.599674,11110,4.153,-73.599651,0.005913,"[1338, 9636]","[1270, 5855]","[821, 3851]",...,"[1180, 7323]","[916, 4298]","[663, 3065]","[1065, 5302]","[777, 3620]","[764, 3946]","[4160, 54048]","[717, 3015]","[4160, 54048]","[4160, 54048]"
4,4,4.148361,-73.613292,14637,4.148,-73.613417,0.042406,"[1160, 9432]","[944, 4376]","[494, 2372]",...,"[1002, 7119]","[589, 2819]","[336, 1586]","[738, 3823]","[451, 2141]","[525, 2068]","[3982, 53844]","[388, 1536]","[3982, 53844]","[3982, 53844]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,4.158273,-73.651119,7341,4.158,-73.651163,0.030774,"[1911, 14381]","[646, 3221]","[890, 5444]",...,"[1571, 10635]","[570, 3406]","[677, 4268]","[973, 5243]","[620, 3860]","[1192, 6860]","[4433, 55849]","[1021, 6117]","[4433, 55849]","[4433, 55849]"
196,196,4.103017,-73.659508,45497,4.103,-73.659841,0.036985,"[1977, 17208]","[975, 6919]","[952, 7112]",...,"[1249, 10245]","[921, 7172]","[916, 7580]","[763, 5873]","[858, 7172]","[1181, 8113]","[4111, 55459]","[1187, 8248]","[4111, 55459]","[4111, 55459]"
197,197,4.155809,-73.632643,8546,4.156,-73.632766,0.025231,"[1547, 11967]","[480, 1854]","[526, 3029]",...,"[1316, 9594]","[206, 991]","[313, 1854]","[678, 3878]","[256, 1445]","[828, 4446]","[4179, 54808]","[656, 3703]","[4179, 54808]","[4179, 54808]"
198,198,4.136147,-73.609554,23612,4.136,-73.609601,0.017196,"[1168, 9322]","[974, 4728]","[448, 1988]",...,"[843, 5995]","[739, 3877]","[487, 2644]","[567, 3006]","[601, 3199]","[169, 454]","[3805, 52038]","[276, 1054]","[3805, 52038]","[3805, 52038]"
199,199,4.119560,-73.609358,37039,4.120,-73.609399,0.049086,"[1395, 11652]","[886, 5925]","[571, 4158]",...,"[715, 5051]","[774, 5523]","[735, 4825]","[479, 3379]","[699, 5488]","[578, 3264]","[3577, 50265]","[681, 4038]","[3577, 50265]","[3577, 50265]"

In [81]:
array_idsede

array([  827,   937,   945,   946,   961,   969,   970,   971,  3876,
        4067,  4068,  4174,  4230,  4231,  5409,  5588,  5888,  6439,
        6440,  6449,  6472,  6473,  6474,  6617,  9710,  9711,  9726,
       10827, 10887, 11756, 11757, 11758, 15123, 15147, 17213, 17225,
       17323, 17343, 17359, 17360, 17379, 17380, 20609, 20610, 20622,
       20623, 20624, 22639, 22783, 22798, 25819, 27262, 27943, 28069,
       28116, 28117, 28118, 31119, 31422, 31433, 32521, 32522, 33473,
       33491, 33585, 33609, 33624, 35091, 36695, 36974, 38150, 38534,
       39041, 39156, 39166, 39193, 39194, 39357, 42458, 42459, 42470,
       42471, 42472, 44022, 44499, 44622, 44623, 44624, 44633, 44634,
       44658, 44659, 44675, 44676, 44677, 44825, 47941, 47942, 49556,
       50086, 50105, 50131, 50132, 50133, 53111, 53406, 53407, 53419,
       54504, 55534, 55535, 55549, 55550, 55558, 55579, 55591, 58580,
       58877, 58884, 60967, 60979, 61175, 62527, 62528, 63981, 65066,
       66136, 66299, 66323, 66324, 66325, 66341, 69339, 69481, 69482,
       71574, 71575, 71576, 71584, 71615, 71616, 71617, 74882, 74897,
       74898, 77000, 77120, 77121, 77129, 77160, 77161, 80410, 81555,
       82443, 82576, 82577, 82595, 82596, 82627, 85626, 85906, 86871,
       87062], dtype=int64)

In [82]:
df3=df2.copy(deep=True)

In [83]:
df3 = df3.drop(array_idsede, axis=1)

In [86]:
for col in array_idsede:
    df3[col] = df2[col].apply(lambda x: x[0])

In [87]:
df3

,Unnamed: 0,x,y,index_vertice_cercano,LATITUD,LONGITUD,distancia_h,827,937,945,...,82443,82576,82577,82595,82596,82627,85626,85906,86871,87062
0,0,4.124433,-73.627487,33483,4.124,-73.627545,0.048541,1623,839,512,...,828,715,649,298,641,686,3690,691,3690,3690
1,1,4.118694,-73.563922,37514,4.119,-73.563647,0.045658,783,1636,1142,...,498,1282,1029,1236,1143,888,4335,994,4335,4335
2,2,4.075202,-73.672954,52077,4.075,-73.672891,0.023477,2358,1356,1333,...,1630,1302,1297,1144,1240,1562,4412,1568,4412,4412
3,3,4.153048,-73.599674,11110,4.153,-73.599651,0.005913,1338,1270,821,...,1180,916,663,1065,777,764,4160,717,4160,4160
4,4,4.148361,-73.613292,14637,4.148,-73.613417,0.042406,1160,944,494,...,1002,589,336,738,451,525,3982,388,3982,3982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,4.158273,-73.651119,7341,4.158,-73.651163,0.030774,1911,646,890,...,1571,570,677,973,620,1192,4433,1021,4433,4433
196,196,4.103017,-73.659508,45497,4.103,-73.659841,0.036985,1977,975,952,...,1249,921,916,763,858,1181,4111,1187,4111,4111
197,197,4.155809,-73.632643,8546,4.156,-73.632766,0.025231,1547,480,526,...,1316,206,313,678,256,828,4179,656,4179,4179
198,198,4.136147,-73.609554,23612,4.136,-73.609601,0.017196,1168,974,448,...,843,739,487,567,601,169,3805,276,3805,3805
199,199,4.119560,-73.609358,37039,4.120,-73.609399,0.049086,1395,886,571,...,715,774,735,479,699,578,3577,681,3577,3577

In [88]:
df3.to_csv("TIEMPOS_VIAJE_SEG_CLUSTERS_COLEGIOSOFICIALES.csv",index=True)

In [89]:
df4=df2.copy(deep=True)

In [90]:
df4 = df4.drop(array_idsede, axis=1)

In [91]:
for col in array_idsede:
    df4[col] = df2[col].apply(lambda x: x[1])

In [92]:
df4

,Unnamed: 0,x,y,index_vertice_cercano,LATITUD,LONGITUD,distancia_h,827,937,945,...,82443,82576,82577,82595,82596,82627,85626,85906,86871,87062
0,0,4.124433,-73.627487,33483,4.124,-73.627545,0.048541,11943,4003,2787,...,5685,4152,3445,1205,4117,3269,50899,3405,50899,50899
1,1,4.118694,-73.563922,37514,4.119,-73.563647,0.045658,5541,11537,9199,...,3620,9980,8747,9575,9302,6640,56462,8488,56462,56462
2,2,4.075202,-73.672954,52077,4.075,-73.672891,0.023477,20737,10448,10641,...,13774,10701,11109,9402,10701,11642,58545,11777,58545,58545
3,3,4.153048,-73.599674,11110,4.153,-73.599651,0.005913,9636,5855,3851,...,7323,4298,3065,5302,3620,3946,54048,3015,54048,54048
4,4,4.148361,-73.613292,14637,4.148,-73.613417,0.042406,9432,4376,2372,...,7119,2819,1586,3823,2141,2068,53844,1536,53844,53844
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,4.158273,-73.651119,7341,4.158,-73.651163,0.030774,14381,3221,5444,...,10635,3406,4268,5243,3860,6860,55849,6117,55849,55849
196,196,4.103017,-73.659508,45497,4.103,-73.659841,0.036985,17208,6919,7112,...,10245,7172,7580,5873,7172,8113,55459,8248,55459,55459
197,197,4.155809,-73.632643,8546,4.156,-73.632766,0.025231,11967,1854,3029,...,9594,991,1854,3878,1445,4446,54808,3703,54808,54808
198,198,4.136147,-73.609554,23612,4.136,-73.609601,0.017196,9322,4728,1988,...,5995,3877,2644,3006,3199,454,52038,1054,52038,52038
199,199,4.119560,-73.609358,37039,4.120,-73.609399,0.049086,11652,5925,4158,...,5051,5523,4825,3379,5488,3264,50265,4038,50265,50265

In [94]:
df4.to_csv("DISTANCIAS_METROS_CLUSTERS_COLEGIOSOFICIALES.csv",index=True)